server:
  port: ":8080"
  requestTimeoutInMillisecond: 50

log:
  filepath: "log.json"
  level: "debug"

database:
  name: "restaurant_service_qa"
  host: "host.docker.internal"
  port: 5432
  username: "pgadmin_user"
  password: "pgadmin@123"
