version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    restart: unless-stopped

volumes:
  postgres_data: null
  pgadmin_data: null

networks:
  backend: null