basePath: /api
definitions:
  data.Product:
    properties:
      description:
        description: Description
        type: string
      id:
        description: Product ID
        type: integer
      name:
        description: Product name
        type: string
      price:
        description: Selling price
        type: number
      sku:
        description: Stock ID, SKU has custom validator
        type: string
    required:
    - name
    - sku
    type: object
host: localhost:8080
info:
  contact:
    email: subhankardas831@gmail.com
    name: Subhankar Das
    url: https://github.com/subhankardas
  description: API documentation for the products service.
  title: Products Service API
  version: 1.0.0
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Returns list of all the products in store.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get list of products.
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Adds a new product to the store.
      parameters:
      - description: Product Details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/data.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Add new product.
      tags:
      - products
  /products/{id}:
    put:
      consumes:
      - application/json
      description: Update product details to the store.
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/data.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Update existing product.
      tags:
      - products
swagger: "2.0"
